apiVersion: apps/v1
kind: Deployment
metadata:
  name: falcon-web
  namespace: falcon
spec:
  replicas: 2
  selector:
    matchLabels:
      app: falcon-web
  template:
    metadata:
      labels:
        app: falcon-web
    spec:
      containers:
      - name: falcon-web
        image: falcon-web:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: falcon-web
  namespace: falcon
spec:
  type: LoadBalancer
  selector:
    app: falcon-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
